# Generated by Django 4.2.7 on 2025-05-24 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('twitter', 'Twitter')], max_length=10)),
                ('model', models.CharField(choices=[('vader', 'VADER'), ('gpt', 'GPT'), ('grok', 'Grok'), ('claude', 'Claude'), ('deepseek', 'DeepSeek')], default='vader', max_length=10)),
                ('subreddits', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('include_images', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sentiment Analyses',
            },
        ),
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('score', models.FloatField()),
                ('compound_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_images', models.BooleanField(default=False)),
                ('sentiment_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sentiment_analysis.sentimentanalysis')),
            ],
            options={
                'unique_together': {('sentiment_analysis', 'post_id')},
            },
        ),
        migrations.CreateModel(
            name='ImageSentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_description', models.TextField(blank=True)),
                ('score', models.FloatField()),
                ('dominant_emotion', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_results', to='sentiment_analysis.sentimentresult')),
            ],
            options={
                'unique_together': {('sentiment_result', 'image_url')},
            },
        ),
    ]
