# Generated by Django 5.2.1 on 2025-05-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0002_remove_imagesentimentresult_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='selected_llms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
