# Generated by Django 5.2.1 on 2025-05-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0003_sentimentanalysis_selected_llms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresult',
            name='is_sarcastic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='sarcasm_score',
            field=models.FloatField(default=0),
        ),
    ]
