# Generated by Django 5.2.1 on 2025-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0006_add_gemma_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresult',
            name='is_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='source',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
