# Generated by Django 5.0.2 on 2025-05-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0007_sentimentresult_is_ad_alter_sentimentanalysis_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='content_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
