# Generated by Django 5.0.2 on 2025-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0008_sentimentanalysis_content_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresult',
            name='grok_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='model',
            field=models.CharField(choices=[('vader', 'VADER'), ('gpt4', 'GPT-4'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('gemma', 'Gemma')], default='vader', max_length=10),
        ),
    ]
